<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Room;
use App\Models\User;
class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $roomseeder = [
            [
                'partner_id' => 1,
                'room_name' => 'Stellar Space Medium',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'U Shape',
                'room_area' => '10 x 7 m²',
                'extra' => '1 extra-large double bed',
                'person' => '5-10 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Projector',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => '',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 499000,
            ],
            [
                'partner_id' => 1,
                'room_name' => 'Stellar Space Small',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'U Shape',
                'room_area' => '10 x 9 m²',
                'extra' => '1 extra-large double bed',
                'person' => '10-20 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Wifi Included',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => '',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 599000,
            ],
            [
                'partner_id' => 1,
                'room_name' => 'Stellar Space Large',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'U Shape',
                'room_area' => '10 x 10 m²',
                'extra' => '1 extra-large double bed',
                'person' => '20-30 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Projector',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => 'Wifi Included',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 799000,
            ],
            [
                'partner_id' => 1,
                'room_name' => 'Buah Batu Meeting',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'Openspace',
                'room_area' => '10 x 10 m²',
                'extra' => '1 extra-large double bed',
                'person' => '20-30 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Projector',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => 'Wifi Included',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 399000,
            ],
            [
                'partner_id' => 1,
                'room_name' => 'Stellar Lembang Indoor',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'Indoor',
                'room_area' => '10 x 13 m²',
                'extra' => '1 extra-large double bed',
                'person' => '15-20 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Projector',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => 'Wifi Included',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 459000,
            ],
            [
                'partner_id' => 1,
                'room_name' => 'Stellar Lembang Openspace',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'Openspace',
                'room_area' => '10 x 13 m²',
                'extra' => '1 extra-large double bed',
                'person' => '15-20 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Projector',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => 'Wifi Included',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 459000,
            ],
            [
                'partner_id' => 1,
                'room_name' => 'Stellar Cikarang Lounge',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'Lounge',
                'room_area' => '10 x 13 m²',
                'extra' => '1 extra-large double bed',
                'person' => '15-20 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Projector',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => 'Wifi Included',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 459000,
            ],
            [
                'partner_id' => 1,
                'room_name' => 'Stellar Lembang Indoor',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'Indoor',
                'room_area' => '10 x 13 m²',
                'extra' => '1 extra-large double bed',
                'person' => '15-20 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Projector',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => 'Wifi Included',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 459000,
            ],
            [
                'partner_id' => 1,
                'room_name' => 'Stellar Mekar Wangi Lounge',
                'address1' => 'jl buah batu',
                'address2' => 'jl buah batu',
                'subdistrict' => 'Buah Batu',
                'city' => 'Bandung',
                'zipcode' => '17530',
                'room_type' => 'Lounge',
                'room_area' => '10 x 13 m²',
                'extra' => '1 extra-large double bed',
                'person' => '15-20 Person',
                'room_description' => 'Providing lake views, The Symphony 9 Tam Coc in Ninh Binh provides accommodation, an outdoor swimming pool, a bar, a shared lounge, a garden and barbecue facilities. Complimentary WiFi is provided.

                There is a private bathroom with bidet in all units, a',
                'properties1' => 'Speaker',
                'properties2' => 'Projector',
                'properties3' => 'Whiteboard',
                'properties4' => 'Charging port',
                'properties5' => 'Food and Baverage',
                'properties6' => 'Free Cancellation',
                'properties7' => 'Wifi Included',
                'properties8' => '',
                'special_note' => '',
                'foto1' => 'foto1.png',
                'foto2' => 'foto2.png',
                'foto3' => 'foto3.png',
                'foto4' => 'foto3.png',
                'price' => 459000,
            ],
        ];

        Room::insert($roomseeder);
        \App\Models\User::factory(2)->create();
    }
}
